// Re-export all types
export * from './api.js';
export * from './config.js';
export * from './common.js';
export * from './validation.js';

// Re-export CLI types except SearchOptions to avoid conflict
export type { 
  GlobalOptions,
  BaseCommandOptions,
  TUIOptions,
  ConfigInitOptions,
  ConfigShowOptions,
  ConfigSetOptions,
  ProfileListOptions,
  ProfileShowOptions,
  ProfileCreateOptions,
  ProfileDeleteOptions,
  ProfileSetOptions,
  ProfileCopyOptions,
  ProfileConfigureOptions,
  NoteCreateOptions,
  NoteGetOptions,
  NoteUpdateOptions,
  NoteDeleteOptions,
  NoteListOptions,
  NoteExportOptions,
  NoteImportOptions,
  NoteMoveOptions,
  NoteCloneOptions,
  SearchOptions as CLISearchOptions,
  BranchCreateOptions,
  BranchListOptions,
  BranchUpdateOptions,
  BranchDeleteOptions,
  AttributeCreateOptions,
  AttributeListOptions,
  AttributeUpdateOptions,
  AttributeDeleteOptions,
  AttachmentUploadOptions,
  AttachmentDownloadOptions,
  AttachmentListOptions,
  AttachmentInfoOptions,
  AttachmentDeleteOptions,
  BackupOptions,
  CalendarOptions,
  PipeOptions,
  LinkBacklinksOptions,
  LinkOutgoingOptions,
  LinkBrokenOptions,
  LinkUpdateOptions,
  LinkValidateOptions,
  TagListOptions,
  TagSearchOptions,
  TagCloudOptions,
  TagAddOptions,
  TagRemoveOptions,
  TagRenameOptions,
  TemplateListOptions,
  TemplateCreateOptions,
  TemplateShowOptions,
  TemplateUseOptions,
  TemplateUpdateOptions,
  TemplateDeleteOptions,
  TemplateValidateOptions,
  QuickOptions,
  ImportObsidianOptions,
  ExportObsidianOptions,
  ImportNotionOptions,
  ExportNotionOptions,
  ImportDirOptions,
  SyncGitOptions,
  PluginListOptions,
  PluginInstallOptions,
  PluginUninstallOptions,
  PluginEnableOptions,
  PluginDisableOptions,
  PluginInfoOptions,
  PluginRunOptions,
  CompletionGenerateOptions,
  CompletionInstallOptions,
  CompletionCacheClearOptions,
  CompletionCacheStatusOptions,
  CompletionCacheRefreshOptions
} from './cli.js';